In [10]:
%load_ext kedro.ipython

The kedro.ipython extension is already loaded. To reload it, use:
  %reload_ext kedro.ipython

In [11]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Carga de los 4 archivos registrados catalog.yml 
df_ventas = catalog.load("ventas_raw")
df_productos = catalog.load("productos_raw")
df_clientes = catalog.load("clientes_raw")
df_devoluciones = catalog.load("devoluciones_raw")

[04/07/26 14:24:38] INFO     Loading data from ventas_raw (CSVDataset)...                      ]8;id=815459;file://C:\Users\alarc\OneDrive\Escritorio\evaluacion-parcial-1\evaluacion-parcial-1\.venv\Lib\site-packages\kedro\io\data_catalog.py\data_catalog.py]8;;\:]8;id=878775;file://C:\Users\alarc\OneDrive\Escritorio\evaluacion-parcial-1\evaluacion-parcial-1\.venv\Lib\site-packages\kedro\io\data_catalog.py#1048\1048]8;;\

                    INFO     Loading data from productos_raw (CSVDataset)...                   ]8;id=206132;file://C:\Users\alarc\OneDrive\Escritorio\evaluacion-parcial-1\evaluacion-parcial-1\.venv\Lib\site-packages\kedro\io\data_catalog.py\data_catalog.py]8;;\:]8;id=782817;file://C:\Users\alarc\OneDrive\Escritorio\evaluacion-parcial-1\evaluacion-parcial-1\.venv\Lib\site-packages\kedro\io\data_catalog.py#1048\1048]8;;\

                    INFO     Loading data from clientes_raw (CSVDataset)...                    ]8;id=579485;file://C:\Users\alarc\OneDrive\Escritorio\evaluacion-parcial-1\evaluacion-parcial-1\.venv\Lib\site-packages\kedro\io\data_catalog.py\data_catalog.py]8;;\:]8;id=586332;file://C:\Users\alarc\OneDrive\Escritorio\evaluacion-parcial-1\evaluacion-parcial-1\.venv\Lib\site-packages\kedro\io\data_catalog.py#1048\1048]8;;\

                    INFO     Loading data from devoluciones_raw (CSVDataset)...                ]8;id=613384;file://C:\Users\alarc\OneDrive\Escritorio\evaluacion-parcial-1\evaluacion-parcial-1\.venv\Lib\site-packages\kedro\io\data_catalog.py\data_catalog.py]8;;\:]8;id=853492;file://C:\Users\alarc\OneDrive\Escritorio\evaluacion-parcial-1\evaluacion-parcial-1\.venv\Lib\site-packages\kedro\io\data_catalog.py#1048\1048]8;;\

In [12]:
print("--- Estructura de Ventas ---")
display(df_ventas.shape)
display(df_ventas.dtypes)
display(df_ventas.head())
display(df_ventas.describe())
df_ventas.info()

--- Estructura de Ventas ---

(1030, 8)

id_venta           float64
fecha                  str
id_cliente         float64
id_producto        float64
cantidad           float64
precio_unitario        str
metodo_pago            str
canal_venta            str
dtype: object

,id_venta,fecha,id_cliente,id_producto,cantidad,precio_unitario,metodo_pago,canal_venta
0,NaN,01/01/2023,26.0,128.0,1.0,411094.0,Tarjeta Crédito,Web
1,2.0,2023-01-01,47.0,111.0,8.0,330096.0,Tarjeta Débito,Web
2,3.0,02/01/2023,288.0,136.0,19.0,398324.0,WEBPAY,Tienda Física
3,4.0,2023-01-03,266.0,106.0,NaN,136701.0,Webpay,Tienda Física
4,5.0,03/01/2023,16.0,186.0,3.0,346487.0,Webpay,Marketplace

          id_venta  id_cliente  id_producto     cantidad
count   977.000000  974.000000   981.000000   979.000000
mean    502.127943  152.074949   104.492355    19.747702
std     288.050515   87.180499    56.755016   103.569991
min       2.000000    1.000000     1.000000   -85.000000
25%     253.000000   79.000000    57.000000     5.000000
50%     501.000000  152.000000   108.000000    10.000000
75%     749.000000  227.000000   154.000000    15.000000
max    1000.000000  300.000000   200.000000  1900.000000

<class 'pandas.DataFrame'>
RangeIndex: 1030 entries, 0 to 1029
Data columns (total 8 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   id_venta         977 non-null    float64
 1   fecha            984 non-null    str
 2   id_cliente       974 non-null    float64
 3   id_producto      981 non-null    float64
 4   cantidad         979 non-null    float64
 5   precio_unitario  985 non-null    str
 6   metodo_pago      973 non-null    str
 7   canal_venta      985 non-null    str
dtypes: float64(4), str(4)
memory usage: 101.2 KB

In [13]:
print("--- Estructura de Productos ---")
display(df_productos.shape)
display(df_productos.dtypes)
display(df_productos.head())
display(df_productos.describe())
df_ventas.info()

--- Estructura de Productos ---

(206, 7)

id_producto     float64
nombre              str
categoria           str
subcategoria        str
precio_lista    float64
stock           float64
proveedor           str
dtype: object

,id_producto,nombre,categoria,subcategoria,precio_lista,stock,proveedor
0,1.0,Producto_1,Belleza,Sub_A,325332.0,226.0,ProvE
1,2.0,Producto_2,Deportes,Sub_E,351281.0,146.0,ProvB
2,3.0,Producto_3,Alimentos,Sub_D,398101.0,19.0,ProvF
3,4.0,Producto_4,Belleza,Sub_D,NaN,440.0,ProvE
4,5.0,Producto_5,Hogar,Sub_D,169660.0,401.0,ProvB

       id_producto   precio_lista       stock
count   199.000000     194.000000  196.000000
mean    101.206030  239337.932990  252.025510
std      58.267433  152959.879523  142.771161
min       1.000000    6408.000000    0.000000
25%      51.500000   87439.500000  132.000000
50%     101.000000  241964.500000  254.500000
75%     151.500000  374986.750000  372.000000
max     200.000000  496489.000000  495.000000

<class 'pandas.DataFrame'>
RangeIndex: 1030 entries, 0 to 1029
Data columns (total 8 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   id_venta         977 non-null    float64
 1   fecha            984 non-null    str
 2   id_cliente       974 non-null    float64
 3   id_producto      981 non-null    float64
 4   cantidad         979 non-null    float64
 5   precio_unitario  985 non-null    str
 6   metodo_pago      973 non-null    str
 7   canal_venta      985 non-null    str
dtypes: float64(4), str(4)
memory usage: 101.2 KB

In [14]:
print("--- Estructura de Clientes ---")
display(df_clientes.shape)
display(df_clientes.dtypes)
display(df_clientes.head())
display(df_clientes.describe())
df_ventas.info()

--- Estructura de Clientes ---

(309, 7)

id_cliente        float64
nombre                str
email                 str
region                str
ciudad                str
fecha_registro        str
segmento              str
dtype: object

,id_cliente,nombre,email,region,ciudad,fecha_registro,segmento
0,NaN,Cristóbal Silva Muñoz,cristóbal.silva@gmail.com,Los Lagos,Osorno,2020-01-01,Regular
1,2.0,Fernanda García Hernández,fernanda.garcía@outlook.com,Coquimbo,La Serena,2020-01-03,Regular
2,3.0,Andrés Contreras Soto,NaN,O'Higgins,Rengo,2020-01-05,Regular
3,NaN,Natalia Tapia Rojas,natalia.tapia@gmail.com,Los Lagos,Osorno,07/01/2020,VIP
4,5.0,José Soto Fuentes,josé.soto@gmail.com,Biobío,Concepción,2020-01-09,Premium

       id_cliente
count  295.000000
mean   152.447458
std     86.408792
min      2.000000
25%     78.500000
50%    153.000000
75%    227.500000
max    300.000000

<class 'pandas.DataFrame'>
RangeIndex: 1030 entries, 0 to 1029
Data columns (total 8 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   id_venta         977 non-null    float64
 1   fecha            984 non-null    str
 2   id_cliente       974 non-null    float64
 3   id_producto      981 non-null    float64
 4   cantidad         979 non-null    float64
 5   precio_unitario  985 non-null    str
 6   metodo_pago      973 non-null    str
 7   canal_venta      985 non-null    str
dtypes: float64(4), str(4)
memory usage: 101.2 KB

In [15]:
print("--- Estructura de Devoluciones ---")
display(df_devoluciones.shape)
display(df_devoluciones.dtypes)
display(df_devoluciones.head())
display(df_devoluciones.describe())
df_ventas.info()

--- Estructura de Devoluciones ---

(154, 5)

id_devolucion       float64
id_venta            float64
fecha_devolucion        str
motivo                  str
estado                  str
dtype: object

   id_devolucion  id_venta fecha_devolucion             motivo       estado
0            1.0       NaN       2023-02-01   Talla incorrecta  En revisión
1            2.0      88.0       2023-02-05       Llegó dañado    Pendiente
2            3.0     991.0       10/02/2023       Llegó dañado          NaN
3            4.0     977.0       2023-02-15  No es lo esperado    Rechazada
4            5.0     349.0       2023-02-20         Defectuoso    Pendiente

       id_devolucion    id_venta
count     150.000000  147.000000
mean       74.900000  509.115646
std        43.717481  292.364440
min         1.000000    8.000000
25%        36.250000  248.500000
50%        74.500000  504.000000
75%       112.750000  768.500000
max       150.000000  998.000000

<class 'pandas.DataFrame'>
RangeIndex: 1030 entries, 0 to 1029
Data columns (total 8 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   id_venta         977 non-null    float64
 1   fecha            984 non-null    str
 2   id_cliente       974 non-null    float64
 3   id_producto      981 non-null    float64
 4   cantidad         979 non-null    float64
 5   precio_unitario  985 non-null    str
 6   metodo_pago      973 non-null    str
 7   canal_venta      985 non-null    str
dtypes: float64(4), str(4)
memory usage: 101.2 KB

In [16]:
# Detectar nulos y duplicados en todos los datasets 
for nombre, df in [("Ventas", df_ventas), ("Productos", df_productos), 
                  ("Clientes", df_clientes), ("Devoluciones", df_devoluciones)]:
    print(f"\nDiagnóstico {nombre}:")
    print(f"- Nulos totales: {df.isnull().sum().sum()}")
    print(f"- Filas duplicadas: {df.duplicated().sum()}")

Diagnóstico Ventas:
- Nulos totales: 402
- Filas duplicadas: 30

Diagnóstico Productos:
- Nulos totales: 72
- Filas duplicadas: 6

Diagnóstico Clientes:
- Nulos totales: 105
- Filas duplicadas: 9

Diagnóstico Devoluciones:
- Nulos totales: 36
- Filas duplicadas: 4

In [23]:
def preprocess_ventas(df: pd.DataFrame) -> pd.DataFrame:
    df_clean = df.copy().drop_duplicates()
    df_clean = df_clean.dropna(subset=['id_venta', 'id_cliente', 'id_producto'])
    
    df_clean['fecha'] = pd.to_datetime(df_clean['fecha'], dayfirst=True, errors='coerce')
    df_clean = df_clean.dropna(subset=['fecha'])
    
    cols_str = ['metodo_pago', 'canal_venta']
    for col in cols_str:
        if col in df_clean.columns:
            df_clean[col] = df_clean[col].astype(str).str.strip().str.title()
            df_clean[col] = df_clean[col].replace('Nan', np.nan)
            df_clean[col] = df_clean[col].fillna(df_clean[col].mode()[0])
            
    cols_num = ['precio_unitario', 'cantidad']
    for col in cols_num:
        if col in df_clean.columns:
            df_clean[col] = pd.to_numeric(df_clean[col], errors='coerce')
            df_clean[col] = df_clean[col].fillna(df_clean[col].median())
    
    return df_clean

In [24]:
def preprocess_productos(df: pd.DataFrame) -> pd.DataFrame:
    df_clean = df.copy().drop_duplicates()
    df_clean = df_clean.dropna(subset=['id_producto']) 
    
    cols_str = ['categoria', 'subcategoria', 'proveedor']
    for col in cols_str:
        if col in df_clean.columns:
            df_clean[col] = df_clean[col].astype(str).str.strip().str.title()
            df_clean[col] = df_clean[col].replace('Nan', np.nan)
            df_clean[col] = df_clean[col].fillna(df_clean[col].mode()[0])
            
    cols_num = ['precio_lista', 'stock']
    for col in cols_num:
        if col in df_clean.columns:
            df_clean[col] = pd.to_numeric(df_clean[col], errors='coerce')
            df_clean[col] = df_clean[col].fillna(df_clean[col].median())
            
    return df_clean

In [25]:
def preprocess_clientes(df: pd.DataFrame) -> pd.DataFrame:
    df_clean = df.copy().drop_duplicates()
    df_clean = df_clean.dropna(subset=['id_cliente'])
    
    df_clean['fecha_registro'] = pd.to_datetime(df_clean['fecha_registro'], dayfirst=True, errors='coerce')
    df_clean = df_clean.dropna(subset=['fecha_registro'])
    
    cols_str = ['region', 'ciudad', 'segmento']
    for col in cols_str:
        if col in df_clean.columns:
            df_clean[col] = df_clean[col].astype(str).str.strip().str.title()
            df_clean[col] = df_clean[col].replace('Nan', np.nan)
            df_clean[col] = df_clean[col].fillna(df_clean[col].mode()[0])
            
    return df_clean

In [26]:
def preprocess_devoluciones(df: pd.DataFrame) -> pd.DataFrame:
    df_clean = df.copy().drop_duplicates()
    df_clean = df_clean.dropna(subset=['id_devolucion', 'id_venta'])
    
    df_clean['fecha_devolucion'] = pd.to_datetime(df_clean['fecha_devolucion'], dayfirst=True, errors='coerce')
    df_clean = df_clean.dropna(subset=['fecha_devolucion'])
    
    cols_str = ['motivo', 'estado']
    for col in cols_str:
        if col in df_clean.columns:
            df_clean[col] = df_clean[col].astype(str).str.strip().str.title()
            df_clean[col] = df_clean[col].replace('Nan', np.nan)
            df_clean[col] = df_clean[col].fillna(df_clean[col].mode()[0])
            
    return df_clean

In [27]:
# === EJECUCIÓN Y VERIFICACIÓN DE LIMPIEZA ===

# 1. Ejecutar las 4 funciones
df_ventas_limpio = preprocess_ventas(df_ventas)
df_productos_limpio = preprocess_productos(df_productos)
df_clientes_limpio = preprocess_clientes(df_clientes)
df_devoluciones_limpio = preprocess_devoluciones(df_devoluciones)

# 2. Verificar resultados (Nulos y Duplicados deben ser 0)
datasets_limpios = {
    "Ventas": df_ventas_limpio,
    "Productos": df_productos_limpio,
    "Clientes": df_clientes_limpio,
    "Devoluciones": df_devoluciones_limpio
}

print("=== REPORTE DE VERIFICACIÓN POST-LIMPIEZA ===")
for nombre, df in datasets_limpios.items():
    nulos = df.isnull().sum().sum()
    duplicados = df.duplicated().sum()
    print(f"{nombre}: {nulos} Nulos | {duplicados} Duplicados | Shape: {df.shape}")

=== REPORTE DE VERIFICACIÓN POST-LIMPIEZA ===
Ventas: 0 Nulos | 0 Duplicados | Shape: (151, 8)
Productos: 9 Nulos | 0 Duplicados | Shape: (193, 7)
Clientes: 6 Nulos | 0 Duplicados | Shape: (51, 7)
Devoluciones: 0 Nulos | 0 Duplicados | Shape: (26, 5)